name: Auto-merge Dependabot Updates

on:
  pull_request:
    types: [opened, synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' &&
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      contains(github.event.pull_request.title, 'bump') &&
      (github.event.pull_request.merged == false || github.event.pull_request.merged == null)
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        shell: bash
        run: mvn verify --file pom.xml --batch-mode --update-snapshots

      - name: Merge Dependabot PR
        uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require("@octokit/action");
            const octokit = new Octokit();

            const { data: pullRequest } = await octokit.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            if (pullRequest.state === "open" && pullRequest.mergeable) {
              await octokit.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
              });
            }
