name: Dependabot Automation

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Dependabot PR Auto-Merge
    runs-on: ubuntu-latest

    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.repository == 'philectron/algorithms'

    steps:
      - name: Enable auto-merge
        shell: bash
        run: gh pr merge --auto --merge "${PR_NUMBER}"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
